[tool.pytest.ini_options]
addopts = "--nomigrations"
DJANGO_SETTINGS_MODULE = "project.testing_settings"

[isort]
line_length = 88
known_third_party = [
    "django",
    "factory",
    "test_plus",
]
known_first_party = [
    "users",
]
multi_line_output = 3
include_trailing_comma = true
